/* Generated by Yosys 0.25+3 (git sha1 f2c689403, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module adder(I_A, I_B, O_C);
  wire [4:0] _0_;
  input [3:0] I_A;
  wire [3:0] I_A;
  input [3:0] I_B;
  wire [3:0] I_B;
  output [4:0] O_C;
  wire [4:0] O_C;
  assign _0_ = { 1'h0, I_A } + { 1'h0, I_B };
  assign O_C = _0_;
endmodule
