name: Verilator Regression Test
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.6]

    steps:
      - uses: actions/checkout@v3

      - name: Checkout code
        uses: actions/checkout@v2
    # ... Generate LCOV files or download it from a different job
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
    
      - name: regression
        run: docker run -v ${{ github.workspace }}:/src -w /src/verilator_sim  --entrypoint make verilator/verilator:stable


      - name: Report code coverage
        run : |
          cd verilator_sim
          /usr/bin/genhtml logs/merged.info --output-directory html
        # uses: zgosalvez/github-actions-report-lcov@v3
        # with:
        #   coverage-files: verilator_sim/logs/*.info
        #   minimum-coverage: 60
        #   artifact-name: code-coverage-report
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
          # working-directory: apps/my-first-app
          # update-comment: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          
      # - name: Publish
        # run: bash <(curl -s https://codecov.io/bash) 
